<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-5Q39FUQ" name="Default test" tests="26" failures="2" timestamp="23 Apr 2019 12:02:00 GMT" time="1175.71" errors="0">
  <testcase name="flowMapperTest" time="2.807" classname="tests.FlowMapper"/>
  <testcase name="flowMapperTest" time="61.476" classname="tests.FlowMapper"/>
  <testcase name="flowMapperTest" time="62.204" classname="tests.FlowMapper"/>
  <testcase name="flowMapperTest" time="84.908" classname="tests.FlowMapper"/>
  <testcase name="flowMapperTest" time="28.334" classname="tests.FlowMapper"/>
  <testcase name="flowMapperTest" time="25.281" classname="tests.FlowMapper"/>
  <testcase name="flowMapperTest" time="34.369" classname="tests.FlowMapper"/>
  <testcase name="flowMapperTest" time="56.729" classname="tests.FlowMapper"/>
  <testcase name="flowMapperTest" time="49.186" classname="tests.FlowMapper"/>
  <testcase name="flowMapperTest" time="42.159" classname="tests.FlowMapper"/>
  <testcase name="flowMapperTest" time="56.447" classname="tests.FlowMapper"/>
  <testcase name="flowMapperTest" time="98.923" classname="tests.FlowMapper"/>
  <testcase name="flowMapperTest" time="52.402" classname="tests.FlowMapper">
    <failure type="java.lang.AssertionError" message="expected [23 Apr 2019, 05:23:04 PM] but found [23 Apr 2019, 05:23:04 pm]">
      <![CDATA[java.lang.AssertionError: expected [23 Apr 2019, 05:23:04 PM] but found [23 Apr 2019, 05:23:04 pm]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at in.novopay.platform_ui.pages.web.RBLStatusEnquiryPage.reportsData(RBLStatusEnquiryPage.java:458)
	at in.novopay.platform_ui.pages.web.RBLStatusEnquiryPage.rBLStatusEnquiry(RBLStatusEnquiryPage.java:246)
	at tests.ui.RBLStatusEnquiryTest.rBLStatusEnquiryTest(RBLStatusEnquiryTest.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at tests.FlowMapper.flowMapperTest(FlowMapper.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- flowMapperTest -->
  <testcase name="flowMapperTest" time="71.974" classname="tests.FlowMapper"/>
  <testcase name="flowMapperTest" time="54.204" classname="tests.FlowMapper"/>
  <testcase name="flowMapperTest" time="52.753" classname="tests.FlowMapper"/>
  <testcase name="flowMapperTest" time="31.564" classname="tests.FlowMapper"/>
  <testcase name="flowMapperTest" time="24.814" classname="tests.FlowMapper"/>
  <testcase name="flowMapperTest" time="27.959" classname="tests.FlowMapper"/>
  <testcase name="flowMapperTest" time="29.062" classname="tests.FlowMapper"/>
  <testcase name="flowMapperTest" time="29.08" classname="tests.FlowMapper"/>
  <testcase name="flowMapperTest" time="29.854" classname="tests.FlowMapper"/>
  <testcase name="flowMapperTest" time="33.272" classname="tests.FlowMapper"/>
  <testcase name="flowMapperTest" time="55.582" classname="tests.FlowMapper">
    <failure type="java.lang.AssertionError" message="expected [6.00] but found [6]">
      <![CDATA[java.lang.AssertionError: expected [6.00] but found [6]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at in.novopay.platform_ui.pages.web.ReportsPage.reportsData(ReportsPage.java:251)
	at in.novopay.platform_ui.pages.web.ReportsPage.reports(ReportsPage.java:136)
	at tests.ui.ReportsTest.reportsTest(ReportsTest.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at tests.FlowMapper.flowMapperTest(FlowMapper.java:101)
	at sun.reflect.GeneratedMethodAccessor15.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- flowMapperTest -->
  <testcase name="flowMapperTest" time="26.85" classname="tests.FlowMapper"/>
  <testcase name="flowMapperTest" time="49.317" classname="tests.FlowMapper"/>
</testsuite> <!-- Default test -->
